version: '3.7'
services:
  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - "3000:3000"
  pushgateway:
    restart: always
    image: prom/pushgateway
    ports:
      - "9091:9091"
  prometheus:
    restart: always
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      default:
    links:
      - pushgateway
    depends_on:
      - pushgateway
